services:
  safeway:
    build:
      context: .
      dockerfile: Dockerfile
    image: safeway-scraper:local
    env_file:
      - .env.local
    environment:
      AWS_REGION: $REGION
    volumes:
      - ${HOME}/.aws:/root/.aws:ro
      - ${HOME}/.aws/sso/cache:/root/.aws/sso/cache:ro
    command: >
      python -c "from grocery_god.pipelines.safeway_lambda import handler; print(handler({}, None))"
